# Generated by Django 5.2.15 on 2026-08-15 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farmers', '0002_farmer_district_farmer_pincode_farmer_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Seeds', 'Seeds'), ('Fertilizer', 'Fertilizer'), ('Pesticide', 'Pesticide'), ('Labor', 'Labor'), ('Equipment', 'Equipment'), ('Irrigation', 'Irrigation'), ('Other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='Farmers.farmer')),
            ],
        ),
    ]
