# Generated by Django 5.2.15 on 2026-08-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0001_initial'),
        ('Farmers', '0002_farmer_district_farmer_pincode_farmer_state_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense',
            new_name='Expenses',
        ),
    ]
