# Generated by Django 5.2.15 on 2026-08-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farmers', '0002_farmer_district_farmer_pincode_farmer_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_name', models.CharField(max_length=100)),
                ('survey_number', models.CharField(max_length=50, unique=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soil_type', models.CharField(max_length=100)),
                ('irrigation_type', models.CharField(max_length=100)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='Farmers.farmer')),
            ],
        ),
    ]
