# Generated by Django 5.2.15 on 2026-08-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Seed', 'Seed'), ('Fertilizer', 'Fertilizer'), ('Pesticide', 'Pesticide'), ('Equipment', 'Equipment'), ('Other', 'Other')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('liter', 'Liter'), ('piece', 'Piece'), ('bag', 'Bag')], max_length=20)),
                ('purchase_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
