# Generated by Django 5.2.15 on 2026-08-19 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0002_farmer_district_farmer_pincode_farmer_state_and_more'),
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='Farmers.farmer'),
        ),
    ]
