# Generated by Django 5.2.15 on 2026-08-17 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Crops', '0001_initial'),
        ('Farmers', '0002_farmer_district_farmer_pincode_farmer_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_date', models.DateField()),
                ('buyer', models.CharField(max_length=100)),
                ('Crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='Crops.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='Farmers.farmer')),
            ],
        ),
    ]
