# Generated by Django 5.2.15 on 2026-08-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='district',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='pincode',
            field=models.CharField(default='exit', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='state',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='village',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
