# Generated by Django 5.2.15 on 2026-08-12 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('sowing_date', models.DateField()),
                ('harvest_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='Lands.land')),
            ],
        ),
    ]
